name: Only Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]




jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      DBT_DATASET: yuyuyu
    steps:
      - name: echo
        run: echo ${{github.ref}}

      - name: run2
        run: |
          echo ${DBT_DATASET}
