name: Only Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{github.ref}}

      - name: run
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo RUN-TEST

      - name: set dbt dataset name
        id: dbt
        env:
          DBT_DATASET: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: echo $DBT_DATASET
        shell: bash
