name: Only Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{github.ref}}

      - name: run
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo RUN-TEST

      - name: set dbt dataset env
        run: echo "DBT_DATASET=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_ENV 

      - name: echo dbt dataset env
        run: echo $DBT_DATASET

      - name: dbt run
        env:
          DBT_DATASET: dbt_prod
        run: |
          echo "
          msk_poc:
            target: stg
            outputs:
              stg:
                type: bigquery
                method: oauth
                project: project
                dataset: ${DBT_DATASET}
                threads: 4
                timeout_seconds: 300
                location: asia-northeast1
                priority: interactive
          " >> profiles.yml
          cat ./profiles.yml
          echo $DBT_DATASET
  
